# Generated by Django 3.0.10 on 2023-01-13 19:04

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estancias', '0009_auto_20230113_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(db_column='categoria', help_text='Categoria del evento adverso', max_length=100, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('descripcion', models.CharField(db_column='descripcion', help_text='Descriocion del evento adverso', max_length=500, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('created', models.DateTimeField(auto_now=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventosEstanciaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(db_column='observacion', help_text='Observaciones del evento')),
                ('fecha_evento', models.DateField(db_column='fecha_evento', help_text='Fecha del evento')),
                ('created', models.DateTimeField(auto_now=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('estancia_id', models.ForeignKey(db_column='estancia_id', help_text='Estancia relacionada al evento adverso', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_eventos_adversos', to='estancias.EstanciaModel')),
                ('evento_id', models.ForeignKey(db_column='evento_id', help_text='Id del registro cums del medicamento relacionada', on_delete=django.db.models.deletion.PROTECT, related_name='cums_medicamentos', to='eventos.EventosModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_evento_estancia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventosestanciamodel',
            constraint=models.UniqueConstraint(fields=('estancia_id', 'evento_id', 'fecha_evento'), name='No se puede reportar un mismo evento para una misma estancia el mismo dia'),
        ),
    ]
