# Generated by Django 3.0.10 on 2021-06-01 16:54

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditoria', '0003_fugasauditoriamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoGlosaAuditoriaModel',
            fields=[
                ('codigo', models.PositiveIntegerField(help_text='Codigo del tipo de glosa', primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigits])),
                ('description', models.TextField(help_text='glosa', max_length=180, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_tipo_glosa_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
