# Generated by Django 3.0.10 on 2021-06-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_tipoglosaauditoriamodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fugasauditoriamodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tipoglosaauditoriamodel',
            name='owner',
        ),
        migrations.DeleteModel(
            name='fallasAuditoriaModel',
        ),
        migrations.DeleteModel(
            name='fugasAuditoriaModel',
        ),
        migrations.DeleteModel(
            name='tipoGlosaAuditoriaModel',
        ),
    ]
