# Generated by Django 3.0.10 on 2021-06-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0010_tiporequerimientoauditoriamodel'),
        ('auditoria', '0010_tipofallasauditoriamodel'),
    ]

    operations = [
    ]
