# Generated by Django 3.0.10 on 2021-06-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0011_merge_20210618_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tipoFallasAuditoriaModel',
        ),
    ]
