# Generated by Django 3.0.10 on 2021-06-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0014_tipooportunidadauditoriamodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tipoOportunidadAuditoriaModel',
        ),
    ]
