# Generated by Django 3.0.10 on 2021-03-19 01:46

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cupsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cie10Model',
            fields=[
                ('capitulo', models.IntegerField(help_text='Capitulo CIE10', validators=[django.core.validators.MinValueValidator(0)])),
                ('codigo', models.CharField(help_text='Codigo CIE10', max_length=4, primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('titulo', models.CharField(help_text='Descripcion CIE10', max_length=250, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_cie10', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
