# Generated by Django 3.0.10 on 2021-03-19 01:46

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cie10model'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpsModel',
            fields=[
                ('codigo_habilitacion', models.CharField(help_text='Codigo Habilitacion', max_length=50, primary_key=True, serialize=False, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigits])),
                ('ips', models.CharField(help_text='Nombre de la IPS', max_length=120, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('nit', models.CharField(help_text='Nit de la IPS', max_length=50, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigits])),
                ('sucursal', models.CharField(default='01', help_text='Sucursal IPS', max_length=2, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigits])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_create_ips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
