# Generated by Django 3.0.10 on 2021-03-19 01:47

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tipodocumentomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, help_text='Descripcion Producto', max_length=250, validators=[core.validators.noSpacesStartEnd])),
                ('titular', models.CharField(blank=True, help_text='Titular', max_length=250, validators=[core.validators.noSpacesStartEnd])),
                ('registro_sanitario', models.CharField(help_text='Registro Sanitario', max_length=100, validators=[core.validators.noSpacesStartEnd])),
                ('fecha_expedicion', models.CharField(blank=True, help_text='Fecha expedicion', max_length=20, validators=[core.validators.noSpacesStartEnd])),
                ('fecha_vencimiento', models.CharField(blank=True, help_text='Fecha vencimiento', max_length=20, validators=[core.validators.noSpacesStartEnd])),
                ('estado_registro', models.CharField(blank=True, help_text='Estado registro', max_length=20, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('expediente_cum', models.IntegerField(help_text='Expediente Cum', validators=[django.core.validators.MinValueValidator(0)])),
                ('consecutivo_cum', models.IntegerField(help_text='Consecutivo Cum', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('cantidad_cum', models.IntegerField(help_text='Cantidad Cum', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1999)])),
                ('descripcion_comercial', models.CharField(blank=True, help_text='Descripcion comercial', max_length=300, validators=[core.validators.noSpacesStartEnd])),
                ('estado_cum', models.CharField(blank=True, help_text='Estado Cum', max_length=10, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('fecha_activo', models.CharField(blank=True, help_text='Fecha activo', max_length=20, validators=[core.validators.noSpacesStartEnd])),
                ('fecha_inactivo', models.CharField(blank=True, help_text='Fecha inactivo', max_length=20, validators=[core.validators.noSpacesStartEnd])),
                ('muestra_medica', models.CharField(blank=True, help_text='Muestra medica', max_length=2, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('unidad', models.CharField(blank=True, help_text='Unidad medicamento', max_length=3, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('atc', models.CharField(help_text='Codigo cums', max_length=10, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('descripcion_atc', models.CharField(blank=True, help_text='Descripcion Codigo', max_length=200, validators=[core.validators.noSpacesStartEnd])),
                ('via_administracion', models.CharField(blank=True, help_text='Via administracion', max_length=200, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('concentracion', models.CharField(blank=True, help_text='Concentracion', max_length=2, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('principio_activo', models.CharField(blank=True, help_text='Principio activo', max_length=250, validators=[core.validators.noSpacesStartEnd])),
                ('unidad_medida', models.CharField(blank=True, help_text='Unidad medida', max_length=3, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('cantidad', models.CharField(blank=True, help_text='Cantidad', max_length=10, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigitsAndPoints])),
                ('unidad_referencia', models.CharField(blank=True, help_text='Unidad referencia', max_length=250, validators=[core.validators.noSpacesStartEnd])),
                ('forma_farmaceutica', models.CharField(blank=True, help_text='Forma farmaceutica', max_length=250, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_cums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
