# Generated by Django 3.0.10 on 2021-03-19 01:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cumsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexoModel',
            fields=[
                ('codigo', models.CharField(help_text='Caracter de Sexo', max_length=1, primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('description', models.CharField(help_text='Descripcion', max_length=10, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
