# Generated by Django 3.0.10 on 2021-03-19 01:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sexomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoModel',
            fields=[
                ('codigo', models.CharField(help_text='Codigo Departamento', max_length=5, primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigits])),
                ('description', models.CharField(help_text='Descripcion departamento', max_length=50, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipioModel',
            fields=[
                ('codigo', models.CharField(help_text='Codigo Municipio', max_length=5, primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigits])),
                ('description', models.CharField(help_text='Descripcion municipio', max_length=50, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
