# Generated by Django 3.0.10 on 2021-03-19 01:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_zonaresidenciamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosConsultaModel',
            fields=[
                ('codigo', models.CharField(help_text='Codigo de la consulta', max_length=10, primary_key=True, serialize=False, validators=[core.validators.facturaType])),
                ('description', models.CharField(help_text='Descripcion del codigo de la consulta', max_length=50, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
