# Generated by Django 3.0.10 on 2021-03-23 20:18

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_codigosconsultamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CifModel',
            fields=[
                ('codigo', models.CharField(help_text='Codigo CIF', max_length=6, primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('titulo', models.CharField(help_text='Descripcion CIF', max_length=250, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_cif', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
