# Generated by Django 3.0.10 on 2021-03-23 20:19

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_estadocivilmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPoblacionalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descripción del grupo poblacional', max_length=150, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
