# Generated by Django 3.0.10 on 2021-03-23 20:19

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_grupopoblacionalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcupacionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(help_text='Codigo de la ocupación', unique=True, validators=[core.validators.onlyDigits])),
                ('description', models.CharField(help_text='Ocupación', max_length=180, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersSpacesAndPunctuation])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
