# Generated by Django 3.0.10 on 2021-03-23 21:45

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_vulnerabilidadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origenetnicomodel',
            name='description',
            field=models.CharField(help_text='Descripción del grupo étnico', max_length=80, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces]),
        ),
    ]
