# Generated by Django 3.0.10 on 2021-03-24 03:18

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210324_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipiomodel',
            name='description',
            field=models.CharField(help_text='Descripcion municipio', max_length=50, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces]),
        ),
    ]
