# Generated by Django 3.0.10 on 2021-03-24 03:30

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210324_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonaresidenciamodel',
            name='description',
            field=models.CharField(help_text='Descripcion codigo zona residencia', max_length=100, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces]),
        ),
    ]
