# Generated by Django 3.0.10 on 2021-03-24 03:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210324_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonaresidenciamodel',
            name='latitud',
            field=models.DecimalField(decimal_places=15, help_text='latitud de la zona de residencia', max_digits=20, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigitsAndPoints]),
        ),
    ]
