# Generated by Django 3.0.10 on 2021-03-24 04:08

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210324_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonaresidenciamodel',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='latitud de la zona de residencia', max_digits=16, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigitsAndPoints]),
        ),
        migrations.AlterField(
            model_name='zonaresidenciamodel',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='longitud de la zona de residencia', max_digits=16, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigitsAndPoints]),
        ),
    ]
