# Generated by Django 3.0.10 on 2021-03-25 15:14

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210324_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumsmodel',
            name='descripcion_comercial',
            field=models.CharField(blank=True, help_text='Descripcion comercial', max_length=650, validators=[core.validators.noSpacesStartEnd]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='principio_activo',
            field=models.CharField(blank=True, help_text='Principio activo', max_length=400, validators=[core.validators.noSpacesStartEnd]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Unidad medida', max_length=25, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters]),
        ),
    ]
