# Generated by Django 3.0.10 on 2021-03-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210325_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsmodel',
            name='departamento_id',
            field=models.ForeignKey(db_column='departamento_id', help_text='Codigo del departamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ips_departamento', to='core.DepartamentoModel'),
        ),
        migrations.AddField(
            model_name='ipsmodel',
            name='municipio_id',
            field=models.ForeignKey(db_column='municipio_id', help_text='Código municipio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ips_municipio', to='core.MunicipioModel'),
        ),
    ]
