# Generated by Django 3.0.10 on 2021-03-26 21:28

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210326_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsmodel',
            name='nit',
            field=models.CharField(help_text='Nit de la IPS', max_length=50, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigits]),
        ),
    ]
