# Generated by Django 3.0.10 on 2021-03-26 21:37

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210326_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsmodel',
            name='codigo_habilitacion',
            field=models.CharField(help_text='Codigo Habilitacion', max_length=50, primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigits]),
        ),
    ]
