# Generated by Django 3.0.10 on 2021-03-27 01:21

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210326_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsmodel',
            name='ips',
            field=models.CharField(help_text='Nombre de la IPS', max_length=120, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces]),
        ),
    ]
