# Generated by Django 3.0.10 on 2021-04-07 22:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210327_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaisModel',
            fields=[
                ('codigo', models.PositiveIntegerField(help_text='Codigo del pais', validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigits])),
                ('iso2', models.CharField(help_text='Código identificación ISO2 del país', max_length=2, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('iso3', models.CharField(help_text='Código identificación ISO3 del país', max_length=3, primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('description', models.CharField(help_text='Descripcion (nombre) Pais', max_length=60, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('active', models.BooleanField(default=True)),
            ],
        )
    ]
