# Generated by Django 3.0.10 on 2021-05-12 15:05

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210511_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtcModel',
            fields=[
                ('codigo', models.CharField(help_text='Código ATC', max_length=10, primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('nombre', models.CharField(help_text='Nombre del compuesto del ATC', max_length=200, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('nivel', models.IntegerField(help_text='nivel del ATC', validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_create_atc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
