# Generated by Django 3.0.10 on 2021-05-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_atcmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumsmodel',
            name='atc',
        ),
        migrations.AddField(
            model_name='cumsmodel',
            name='atc_id',
            field=models.ForeignKey(db_column='atc_id', help_text='Codigo ATC', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cums_atc', to='core.AtcModel'),
        ),
    ]
