# Generated by Django 3.0.10 on 2021-05-12 17:31

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210512_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumsmodel',
            name='unidad_referencia',
            field=models.CharField(blank=True, help_text='Unidad referencia', max_length=250, null=True, validators=[core.validators.noSpacesStartEnd]),
        ),
    ]
