# Generated by Django 3.0.10 on 2021-05-12 17:38

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210512_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumsmodel',
            name='cantidad',
            field=models.CharField(blank=True, help_text='Cantidad', max_length=10, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigitsAndPoints]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='concentracion',
            field=models.CharField(blank=True, help_text='Concentracion', max_length=2, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='descripcion_atc',
            field=models.CharField(blank=True, help_text='Descripcion Codigo', max_length=200, null=True, validators=[core.validators.noSpacesStartEnd]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='descripcion_comercial',
            field=models.TextField(blank=True, help_text='Descripcion comercial', max_length=650, validators=[core.validators.noSpacesStartEnd]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='estado_cum',
            field=models.CharField(blank=True, help_text='Estado Cum', max_length=10, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='estado_registro',
            field=models.CharField(blank=True, help_text='Estado registro', max_length=20, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='fecha_activo',
            field=models.CharField(blank=True, help_text='Fecha activo', max_length=20, null=True, validators=[core.validators.noSpacesStartEnd]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='fecha_inactivo',
            field=models.CharField(blank=True, help_text='Fecha inactivo', max_length=20, null=True, validators=[core.validators.noSpacesStartEnd]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='forma_farmaceutica',
            field=models.CharField(blank=True, help_text='Forma farmaceutica', max_length=250, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='muestra_medica',
            field=models.CharField(blank=True, help_text='Muestra medica', max_length=2, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='principio_activo',
            field=models.CharField(blank=True, help_text='Principio activo', max_length=400, null=True, validators=[core.validators.noSpacesStartEnd]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='unidad',
            field=models.CharField(blank=True, help_text='Unidad medicamento', max_length=3, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Unidad medida', max_length=25, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters]),
        ),
        migrations.AlterField(
            model_name='cumsmodel',
            name='via_administracion',
            field=models.CharField(blank=True, help_text='Via administracion', max_length=200, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters]),
        ),
    ]
