# Generated by Django 3.0.10 on 2021-05-12 17:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210512_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumsmodel',
            name='descripcion_comercial',
            field=models.TextField(blank=True, help_text='Descripcion comercial', max_length=650, null=True, validators=[core.validators.noSpacesStartEnd]),
        ),
    ]
