# Generated by Django 3.0.10 on 2021-05-13 03:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20210513_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupsmodel',
            name='nombre',
            field=models.CharField(help_text='Nombre CUPS', max_length=300, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces]),
        ),
    ]
