# Generated by Django 3.0.10 on 2022-07-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20220715_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='group_ips',
            field=models.ManyToManyField(blank=True, help_text='Grupo de IPS asociadas al usuario', null=True, to='core.IpsModel'),
        ),
    ]
