# Generated by Django 3.0.10 on 2022-07-15 20:08

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20220715_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phoneNumber',
            field=models.CharField(default=57, help_text='Telefono usuario', max_length=30, validators=[core.validators.onlyDigits]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phoneNumberPrefix',
            field=models.CharField(default='+57', help_text='Prefijo telefono', max_length=3, validators=[core.validators.phoneValidator]),
        ),
    ]
