# Generated by Django 3.0.10 on 2022-07-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20220715_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='group_profile',
            field=models.ManyToManyField(blank=True, help_text='Grupo de permisos para el usuario', to='core.GrupoPerfil'),
        ),
    ]
