# Generated by Django 3.0.10 on 2022-08-10 16:43

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20220715_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosPacienteModel',
            fields=[
                ('codigo', models.CharField(help_text='Estado de paciente o vital del afiliado', max_length=2, primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('description', models.CharField(help_text='Descripcion del estado', max_length=50, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
