# Generated by Django 3.0.10 on 2022-09-19 21:38

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_estadospacientemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohortemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='cohortemodel',
            name='cohorte_id',
            field=models.CharField(default='AAA', help_text='Codigo cohorte', max_length=3, primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters]),
            preserve_default=False,
        ),
    ]
