# Generated by Django 3.0.10 on 2022-12-27 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20220919_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='cie10model',
            name='alto_riesgo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cie10model',
            name='dias_estancia',
            field=models.IntegerField(default=1, help_text='Dias de estancia', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cie10model',
            name='sindromatico',
            field=models.BooleanField(default=False),
        ),
    ]
