# Generated by Django 3.0.10 on 2023-01-06 02:16

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20221227_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposAsesoresModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descripcion del tipo de asesoria', max_length=50, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
