# Generated by Django 3.0.10 on 2023-01-04 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estancias', '0004_auto_20230104_2241'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0056_auto_20221227_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertinencia', models.IntegerField(choices=[(1, 'Pertinente'), (2, 'No Pertienente'), (0, 'Revision')], default=0, help_text='Indica pertinencia. 1: pertiente, 2. no pertinente, 0: revision')),
                ('fecha_pertinencia', models.DateField(blank=True, null=True, verbose_name='Fecha pertinencia')),
                ('observacion_concurrente', models.TextField(blank=True, help_text='Observaciones concurrentes', null=True)),
                ('solicitud_asesoria', models.IntegerField(choices=[(0, 'No Requerido'), (2, 'Requerido'), (3, 'Revisado')], default=0, help_text='Solicitud asesor. 0: no requerido, 1: requerido, 2: revisado, 3: solicitado')),
                ('motivo_revision_asesor', models.TextField(blank=True, help_text='indica porque se necesita revision de un aseror', null=True)),
                ('fecha_asesoria', models.DateField(blank=True, null=True, verbose_name='Fecha asesoria')),
                ('nota_asesor', models.TextField(blank=True, help_text='Nota del asesor', null=True)),
                ('objecion', models.IntegerField(choices=[(0, 'Revision'), (2, 'Objetar'), (3, 'Objetado')], default=0, help_text='Objecion, 0: en revision, 1: objetar, 2: objetado')),
                ('created', models.DateTimeField(auto_now=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('cum', models.ForeignKey(db_column='cum', help_text='Id del registro cums del medicamento relacionada', on_delete=django.db.models.deletion.PROTECT, related_name='cums_medicamentos', to='core.CumsModel')),
                ('estancia_id', models.ForeignKey(db_column='estancia_id', help_text='Estancia relacionada', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_medicamentos', to='estancias.EstanciaModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medicamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
