# Generated by Django 3.0.10 on 2023-01-06 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_tiposasesoresmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicamentos', '0002_auto_20230105_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentomodel',
            name='especialidad_asesoria',
            field=models.ForeignKey(blank=True, db_column='especialidad_asesoria', help_text='Id de la especialidad del asesor relacionada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_asesoria_medicamentos', to='core.TiposAsesoresModel'),
        ),
        migrations.AddField(
            model_name='medicamentomodel',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha solicitud asesoria'),
        ),
        migrations.AddField(
            model_name='medicamentomodel',
            name='usuario_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_solicitud_asesor_medicamentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
