# Generated by Django 3.0.10 on 2023-01-10 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicamentos', '0003_auto_20230106_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentomodel',
            name='fecha_objecion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha objecion'),
        ),
        migrations.AddField(
            model_name='medicamentomodel',
            name='usuario_objecion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_objecion_medicamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicamentomodel',
            name='objecion',
            field=models.IntegerField(choices=[(0, 'Revision'), (1, 'Objetar'), (2, 'Objetado')], default=0, help_text='Objecion, 0: en revision, 1: objetar, 2: objetado'),
        ),
        migrations.AlterField(
            model_name='medicamentomodel',
            name='solicitud_asesoria',
            field=models.IntegerField(choices=[(0, 'No Requerido'), (1, 'Requerido'), (2, 'Revisado')], default=0, help_text='Solicitud asesor. 0: no requerido, 1: requerido, 2: revisado, 3: solicitado'),
        ),
    ]
