# Generated by Django 3.0.10 on 2023-01-10 23:06

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0004_auto_20230110_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentomodel',
            name='fecha_objecion',
        ),
        migrations.RemoveField(
            model_name='medicamentomodel',
            name='usuario_objecion',
        ),
        migrations.AddField(
            model_name='medicamentomodel',
            name='objecion_id',
            field=models.IntegerField(blank=True, help_text='Id objecion', null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigits]),
        ),
        migrations.AlterField(
            model_name='medicamentomodel',
            name='objecion',
            field=models.IntegerField(choices=[(0, 'No Requerido'), (1, 'Objetar'), (2, 'Objetado')], default=0, help_text='Objecion, 0: en revision, 1: objetar, 2: objetado'),
        ),
    ]
