# Generated by Django 3.0.10 on 2021-06-28 20:46

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('censo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoIngresoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descripción del tipo de ingreso del censo', max_length=40, unique=True, validators=[core.validators.noSpacesStartEnd])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_tipo_ingreso_censo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
