# Generated by Django 3.0.10 on 2021-07-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20210513_0357'),
        ('censo', '0005_condicionaltacensomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilecensomodel',
            name='ips',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='censo_upload_ips', to='core.IpsModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfilecensomodel',
            name='errors_json',
            field=models.CharField(blank=True, help_text='Nombre del archivo de registro con errores en formato JSON', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='uploadfilecensomodel',
            name='errors_json_hash',
            field=models.CharField(blank=True, help_text='Hash del archivo de registro con errores en formato json', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='uploadfilecensomodel',
            name='errors_report',
            field=models.CharField(blank=True, help_text='Reporte de los errores encontrados', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='uploadfilecensomodel',
            name='errors_report_hash',
            field=models.CharField(blank=True, help_text='Hash del archivo de reporte de los errores encontrados', max_length=250, null=True),
        ),
    ]
