# Generated by Django 3.0.10 on 2021-07-20 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0006_uploadfilecensomodel_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilecensomodel',
            name='errors',
            field=models.IntegerField(default=0, help_text='Registros con errores', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='uploadfilecensomodel',
            name='errors_file',
            field=models.CharField(blank=True, help_text='Nombre del archivo de registro con errores', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='uploadfilecensomodel',
            name='errors_hash',
            field=models.CharField(blank=True, help_text='Hash del archivo de registro con errores', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='uploadfilecensomodel',
            name='success',
            field=models.IntegerField(default=0, help_text='Registros correctos', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='uploadfilecensomodel',
            name='success_file',
            field=models.CharField(blank=True, help_text='Nombre del archivo con registros correctos', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='uploadfilecensomodel',
            name='success_hash',
            field=models.CharField(blank=True, help_text='Hash del archivo con registros correctos', max_length=250, null=True),
        ),
    ]
