# Generated by Django 3.0.10 on 2022-09-05 21:34

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_estadospacientemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('censo', '0007_auto_20210720_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='censoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(help_text='Fecha de ingreso del paciente', validators=[core.validators.currentDate])),
                ('identificacion', models.CharField(help_text='identificación del paceinte censado', max_length=15, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('fecha_egreso', models.DateField(blank=True, help_text='Fecha de egreso del paciente', null=True, validators=[core.validators.currentDate])),
                ('fecha_censo', models.DateField(help_text='Fecha de recepción del censo del paciente', validators=[core.validators.currentDate])),
                ('dias_estancia', models.PositiveIntegerField(blank=True, help_text='Dias de estancia del paceinte en el censo', validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('reingreso', models.BooleanField(default=False, help_text='Indica si el registro es un reingreso')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('codigo_ips_id', models.ForeignKey(db_column='codigo_ips_id', on_delete=django.db.models.deletion.PROTECT, related_name='censo_ips', to='core.IpsModel')),
                ('condicion_alta_id', models.ForeignKey(blank=True, db_column='condicion_alta_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='censo_condicion_alta', to='censo.condicionAltaCensoModel')),
                ('dx_actual', models.ForeignKey(db_column='dx_actual', on_delete=django.db.models.deletion.PROTECT, related_name='censo_cie10_actual', to='core.Cie10Model')),
                ('dx_egreso', models.ForeignKey(blank=True, db_column='dx_egreso', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='censo_cie10_egreso', to='core.Cie10Model')),
                ('dx_ingreso', models.ForeignKey(db_column='dx_ingreso', on_delete=django.db.models.deletion.PROTECT, related_name='censo_cie10_ingreso', to='core.Cie10Model')),
                ('origen_evento_id', models.ForeignKey(db_column='origen_evento_id', on_delete=django.db.models.deletion.PROTECT, related_name='censo_origen_evento', to='censo.origenEventoModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_censo', to=settings.AUTH_USER_MODEL)),
                ('tipo_habitacion_id', models.ForeignKey(db_column='tipo_habitacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='censo_tipo_habitacion', to='censo.tipoHabitacionModel')),
                ('tipo_identificacion_id', models.ForeignKey(db_column='tipo_identificacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='censo_tipo_documento', to='core.TipoDocumentoModel')),
                ('tipo_ingreso_id', models.ForeignKey(db_column='tipo_ingreso_id', on_delete=django.db.models.deletion.PROTECT, related_name='censo_tipo_ingreso', to='censo.tipoIngresoModel')),
            ],
        ),
    ]
