# Generated by Django 3.0.10 on 2022-09-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0003_auto_20220905_2137'),
        ('censo', '0009_auto_20220905_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='censomodel',
            name='afiliado_id',
            field=models.ForeignKey(db_column='afiliado_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='censo_afiliado', to='afiliados.afiliadoModel'),
            preserve_default=False,
        )
    ]
