# Generated by Django 3.0.10 on 2022-09-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0010_auto_20220905_2137'),
    ]

    operations = [
        
    ]
