# Generated by Django 3.0.10 on 2021-04-05 16:14

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarifarioContratadoModel',
            fields=[
                ('codigo', models.CharField(help_text='Código del tarifario contratado', max_length=10, primary_key=True, serialize=False, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('description', models.CharField(help_text='Descripción del tarifario contratado', max_length=200, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_tarifario_contratado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
