# Generated by Django 3.0.10 on 2021-03-19 02:33

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalidadProcedimientoModel',
            fields=[
                ('description', models.CharField(help_text='Descripcion finalidad del procedimiento', max_length=20, primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_finalidad_procedimiento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
