# Generated by Django 3.0.10 on 2021-03-19 02:36

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0007_tipodxprincipalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaExternaModel',
            fields=[
                ('codigo', models.CharField(help_text='Codigo causa externa', max_length=2, primary_key=True, serialize=False, validators=[core.validators.onlyDigits])),
                ('description', models.CharField(help_text='Descripcion codigo causa externa', max_length=20, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersSpacesAndPunctuation])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_causa_externa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
