# Generated by Django 3.0.10 on 2021-03-19 02:37

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0009_finalidadconsultatomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArchivoModel',
            fields=[
                ('codigo', models.CharField(help_text='Codigo Archivo', max_length=2, primary_key=True, serialize=False, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('description', models.CharField(help_text='Descripcion del tipo de archivo', max_length=200, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharacters])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_tipo_archivo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
