# Generated by Django 3.0.10 on 2021-03-19 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0011_reglasmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='reglasValidacionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivo_validacion', to='rips.TipoArchivoModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_regla_validacion', to=settings.AUTH_USER_MODEL)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regla_validacion', to='rips.reglasModel')),
            ],
        ),
    ]
