# Generated by Django 3.0.10 on 2021-03-19 02:40

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_codigosconsultamodel'),
        ('rips', '0016_tiposerviciomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestador', models.CharField(help_text='Nombre del prestador', max_length=200, validators=[core.validators.onlyCharactersSpacesAndPunctuation])),
                ('numero_documento', models.CharField(help_text='Numero del documento del prestador', max_length=16, validators=[core.validators.onlyCharactersAndDigits])),
                ('numero_factura', models.CharField(help_text='Numero de la Factura', max_length=30, validators=[core.validators.facturaType])),
                ('fecha_expedicion', models.DateField(verbose_name='Fecha Expedicion')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio Facturacion')),
                ('fecha_final', models.DateField(verbose_name='Fecha Finalizacion Facturacion')),
                ('codigo_entidad', models.CharField(help_text='Codigo de la Entidad administradora', max_length=30, validators=[core.validators.facturaType])),
                ('nombre_entidad', models.CharField(help_text='Nombre de la Entidad administradora', max_length=200, validators=[core.validators.onlyCharactersSpacesAndPunctuation])),
                ('numero_contrato', models.CharField(help_text='Numero contrato', max_length=40, null=True, validators=[core.validators.onlyCharactersAndDigits])),
                ('plan_beneficios', models.CharField(help_text='Plan Beneficios', max_length=40, null=True)),
                ('numero_poliza', models.CharField(help_text='Numero Poliza', max_length=40, null=True)),
                ('valor_pago_compartido', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor pago compartido', max_digits=20)),
                ('valor_comision', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor comision', max_digits=20)),
                ('valor_descuentos', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor descuentos', max_digits=20)),
                ('valor_neto_pagar', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor neto a pagar', max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('active', models.BooleanField(default=True)),
                ('codigo_prestador', models.ForeignKey(help_text='Codigo habilitacion del prestador', on_delete=django.db.models.deletion.CASCADE, related_name='codigo_prestador_af', to='core.IpsModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='af_file', to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(help_text='Codigo habilitacion del prestador', on_delete=django.db.models.deletion.CASCADE, related_name='codigo_prestador_af', to='core.TipoDocumentoModel')),
            ],
        ),
        migrations.AddIndex(
            model_name='afmodel',
            index=models.Index(fields=['numero_factura'], name='numero_factura_idx'),
        ),
        migrations.AddIndex(
            model_name='afmodel',
            index=models.Index(fields=['codigo_prestador'], name='codigo_prestador_idx'),
        ),
        migrations.AddIndex(
            model_name='afmodel',
            index=models.Index(fields=['numero_documento'], name='numero_documento_idx'),
        ),
        migrations.AddConstraint(
            model_name='afmodel',
            constraint=models.UniqueConstraint(fields=('codigo_prestador', 'numero_factura'), name='factura unica'),
        ),
    ]
