# Generated by Django 3.0.10 on 2021-03-19 02:41

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_codigosconsultamodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0018_auto_20210319_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identifacion_usuario', models.CharField(help_text='Numero de identificación del usuario', max_length=16, unique=True, validators=[core.validators.onlyCharactersAndDigits])),
                ('codigo_entidad', models.CharField(help_text='Codigo de la Entidad administradora', max_length=30, validators=[core.validators.facturaType])),
                ('primer_apellido', models.CharField(help_text='Primer apellido del usuario', max_length=50, validators=[core.validators.onlyCharactersAndSpaces])),
                ('segundo_apellido', models.CharField(help_text='Segundo apellido del usuario', max_length=50, null=True, validators=[core.validators.onlyCharactersAndSpaces])),
                ('primer_nombre', models.CharField(help_text='Primer nombre del usuario', max_length=50, validators=[core.validators.onlyCharactersAndSpaces])),
                ('segundo_nombre', models.CharField(help_text='Seguno nombre del usuario', max_length=50, null=True, validators=[core.validators.onlyCharactersAndSpaces])),
                ('edad', models.IntegerField(help_text='Edad del usuario', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('active', models.BooleanField(default=True)),
                ('codigo_departamento_residencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sexo_us', to='core.DepartamentoModel')),
                ('codigo_municipio_residencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sexo_us', to='core.MunicipioModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_archivo_us', to=settings.AUTH_USER_MODEL)),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sexo_us', to='core.SexoModel')),
                ('tipo_identificacion_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_identificacion_usuarios_rips', to='core.TipoDocumentoModel')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_usuario_us', to='rips.TipoUsuarioModel')),
                ('unidad_edad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidad_edad_us', to='rips.UnidadEdadModel')),
                ('zona_residencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sexo_us', to='core.ZonaResidenciaModel')),
            ],
        ),
        migrations.AddIndex(
            model_name='usmodel',
            index=models.Index(fields=['numero_identifacion_usuario'], name='numero_ident_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='usmodel',
            index=models.Index(fields=['primer_apellido'], name='primer_apellido_idx'),
        ),
        migrations.AddConstraint(
            model_name='usmodel',
            constraint=models.UniqueConstraint(fields=('tipo_identificacion_usuario', 'numero_identifacion_usuario', 'primer_apellido', 'primer_nombre'), name='registro usuario unico'),
        ),
    ]
