# Generated by Django 3.0.10 on 2021-03-19 02:41

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0019_auto_20210319_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsIntermediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion_usuario', models.CharField(help_text='Tipo de identificacion', max_length=2, null=True, unique=True)),
                ('numero_identifacion_usuario', models.CharField(help_text='Numero de identificación del usuario', max_length=16, unique=True)),
                ('codigo_entidad', models.CharField(help_text='Codigo de la Entidad administradora', max_length=30, null=True)),
                ('tipo_usuario', models.CharField(help_text='Tipo de Usuario', max_length=2, null=True)),
                ('primer_apellido', models.CharField(help_text='Primer apellido del usuario', max_length=50, validators=[core.validators.onlyCharactersAndSpaces])),
                ('segundo_apellido', models.CharField(help_text='Segundo apellido del usuario', max_length=50, null=True, validators=[core.validators.onlyCharactersAndSpaces])),
                ('primer_nombre', models.CharField(help_text='Primer nombre del usuario', max_length=50, validators=[core.validators.onlyCharactersAndSpaces])),
                ('segundo_nombre', models.CharField(help_text='Seguno nombre del usuario', max_length=50, null=True, validators=[core.validators.onlyCharactersAndSpaces])),
                ('edad', models.CharField(help_text='Edad', max_length=4, null=True)),
                ('unidad_edad', models.CharField(help_text='Unidad edad', max_length=2, null=True)),
                ('sexo', models.CharField(help_text='Sexo', max_length=2, null=True)),
                ('codigo_departamento_residencia', models.CharField(help_text='Codigo departamento', max_length=5, null=True)),
                ('codigo_municipio_residencia', models.CharField(help_text='Codigo municipio', max_length=5, null=True)),
                ('zona_residencia', models.CharField(help_text='Zona residencia', max_length=5, null=True)),
                ('estado_validacion', models.IntegerField(default=0, help_text='Estado de la validacion del registro', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_us_intermedia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='usintermediamodel',
            index=models.Index(fields=['numero_identifacion_usuario'], name='numero_ident_usuario_int_idx'),
        ),
        migrations.AddIndex(
            model_name='usintermediamodel',
            index=models.Index(fields=['primer_apellido'], name='primer_apellido_int_idx'),
        ),
        migrations.AddConstraint(
            model_name='usintermediamodel',
            constraint=models.UniqueConstraint(fields=('tipo_identificacion_usuario', 'numero_identifacion_usuario', 'primer_apellido', 'primer_nombre'), name='registro usuario unico intermedia'),
        ),
    ]
