# Generated by Django 3.0.10 on 2021-03-19 02:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0021_auto_20210319_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcIntermediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Numero de la Factura', max_length=40, null=True)),
                ('codigo_prestador', models.CharField(help_text='Codigo del prestador', max_length=20, null=True)),
                ('tipo_identificacion_usuario', models.CharField(help_text='Tipo de identificacion', max_length=10, null=True)),
                ('numero_identifacion_usuario', models.CharField(help_text='Numero de identificación del usuario', max_length=20, null=True)),
                ('fecha_consulta', models.CharField(help_text='Fecha consulta', max_length=22, null=True)),
                ('numero_autorizacion', models.CharField(help_text='Número de autorización', max_length=30, null=True)),
                ('codigo_consulta', models.CharField(help_text='Codigo consulta', max_length=30, null=True)),
                ('codigo_finalidad_consulta', models.CharField(help_text='Finalidad consulta', max_length=30, null=True)),
                ('codigo_causa_externa', models.CharField(help_text='Codigo causa externa', max_length=30, null=True)),
                ('codigo_diagnostico_principal', models.CharField(help_text='Codigo dx principal', max_length=30, null=True)),
                ('codigo_diagnostico_relacionado1', models.CharField(help_text='Codigo dx relacionado 1', max_length=30, null=True)),
                ('codigo_diagnostico_relacionado2', models.CharField(help_text='Codigo dx relacionado 2', max_length=30, null=True)),
                ('codigo_diagnostico_relacionado3', models.CharField(help_text='Codigo dx relacionado 3', max_length=30, null=True)),
                ('codigo_tipo_diagnostico_principal', models.CharField(help_text='Codigo tipo dx principal', max_length=30, null=True)),
                ('estado_validacion', models.IntegerField(default=0, help_text='Estado de la validacion del registro', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)])),
                ('valor_consulta', models.CharField(help_text='Valor de la consulta', max_length=20, null=True)),
                ('valor_cuota_moderadora', models.CharField(help_text='Valor cuota moderadora', max_length=20, null=True)),
                ('valor_neto_pagar', models.CharField(help_text='Valor neto a pagar', max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion', null=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_ac_int', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='acintermediamodel',
            index=models.Index(fields=['numero_factura'], name='numero_fac_aci_idx'),
        ),
        migrations.AddIndex(
            model_name='acintermediamodel',
            index=models.Index(fields=['codigo_prestador'], name='codigo_prestador_aci_idx'),
        ),
        migrations.AddIndex(
            model_name='acintermediamodel',
            index=models.Index(fields=['numero_identifacion_usuario'], name='numero_identifacion_aci_idx'),
        ),
        migrations.AddConstraint(
            model_name='acintermediamodel',
            constraint=models.UniqueConstraint(fields=('numero_factura', 'fecha_consulta', 'codigo_prestador', 'numero_identifacion_usuario', 'numero_autorizacion', 'codigo_finalidad_consulta', 'codigo_consulta', 'codigo_causa_externa', 'codigo_diagnostico_principal', 'codigo_diagnostico_relacionado1', 'codigo_diagnostico_relacionado2', 'codigo_diagnostico_relacionado3', 'codigo_tipo_diagnostico_principal', 'valor_consulta' ), name='registro consultas_int unico'),
        ),
    ]
