# Generated by Django 3.0.10 on 2021-03-19 02:41

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0023_auto_20210319_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApIntermediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Numero de la Factura', max_length=40, null=True)),
                ('codigo_prestador', models.CharField(help_text='Codigo del prestador', max_length=20, null=True)),
                ('tipo_identificacion_usuario', models.CharField(help_text='Tipo de identificacion', max_length=10, null=True)),
                ('numero_identifacion_usuario', models.CharField(help_text='Numero de identificación del usuario', max_length=20, null=True)),
                ('fecha_procedimiento', models.CharField(help_text='Fecha consulta', max_length=22, null=True)),
                ('numero_autorizacion', models.CharField(help_text='Número de autorización', max_length=30, null=True)),
                ('codigo_procedimiento', models.CharField(help_text='Codigo procedimiento', max_length=20, null=True)),
                ('ambito_procedimiento', models.CharField(help_text='Ambito procedimiento', max_length=20, null=True)),
                ('finalidad_procedimiento', models.CharField(help_text='Finalidad procedimiento', max_length=20, null=True)),
                ('codigo_personal_atiende', models.CharField(help_text='Personal que atiende', max_length=20, null=True)),
                ('codigo_diagnostico_principal', models.CharField(help_text='Codigo diagnistico principal', max_length=20, null=True)),
                ('diagnostico_relacionado', models.CharField(help_text='Codigo diagnistico relacionado', max_length=20, null=True)),
                ('complicacion', models.CharField(help_text='Codigo complicacion', max_length=20, null=True)),
                ('forma_realizacion_acto_cx', models.CharField(help_text='Codigo forma realizacion acto cx', max_length=20, null=True)),
                ('valor_procedimiento', models.CharField(help_text='Valor del procedimiento', max_length=22, null=True)),
                ('estado_validacion', models.IntegerField(default=0, help_text='Estado de la validacion del registro', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)], null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion', null=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_af_intermedia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='apintermediamodel',
            index=models.Index(fields=['numero_factura'], name='num_fac_ap_in_idx'),
        ),
        migrations.AddIndex(
            model_name='apintermediamodel',
            index=models.Index(fields=['codigo_prestador'], name='cod_prestador_ap_in_idx'),
        ),
        migrations.AddIndex(
            model_name='apintermediamodel',
            index=models.Index(fields=['numero_identifacion_usuario'], name='num_identifacion_ap_in_idx'),
        ),
        migrations.AddIndex(
            model_name='apintermediamodel',
            index=models.Index(fields=['codigo_procedimiento'], name='cod_procedimiento_ap_in_idx'),
        ),
        migrations.AddConstraint(
            model_name='apintermediamodel',
            constraint=models.UniqueConstraint(fields=('numero_factura', 'codigo_prestador', 'tipo_identificacion_usuario', 'numero_identifacion_usuario', 'codigo_procedimiento', 'ambito_procedimiento', 'finalidad_procedimiento', 'codigo_personal_atiende', 'codigo_diagnostico_principal','diagnostico_relacionado','complicacion','forma_realizacion_acto_cx','valor_procedimiento'), name='registro ap_int unico'),
        ),
    ]
