# Generated by Django 3.0.10 on 2021-03-19 02:42

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_codigosconsultamodel'),
        ('rips', '0024_auto_20210319_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Numero de la Factura', max_length=30, validators=[core.validators.facturaType])),
                ('numero_identifacion_usuario', models.CharField(help_text='Numero de identificación del usuario', max_length=16, validators=[core.validators.onlyCharactersAndDigits])),
                ('fecha_ingreso_usuario', models.DateField(verbose_name='Fecha de ingreso del usuario a observación')),
                ('hora_ingreso_usuario', models.TimeField(verbose_name='Hora de ingreso del usuario a observación')),
                ('numero_autorizacion', models.CharField(help_text='Número de autorización', max_length=20, validators=[core.validators.facturaType])),
                ('fecha_salida_usuario', models.DateField(verbose_name='Fecha de salida del usuario a observación')),
                ('hora_salida_usuario', models.TimeField(verbose_name='Hora de salida del usuario a observación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('active', models.BooleanField(default=True)),
                ('causa_basica_muerte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causa_basica_muerte_urgencias', to='core.Cie10Model')),
                ('codigo_causa_externa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causa_externa_urgencias', to='rips.CausaExternaModel')),
                ('codigo_destino_salida_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destino_salida_urgencias', to='rips.DestionSalidaObsModel')),
                ('codigo_estado_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_salida_urgencias', to='rips.EstadoSalidaModel')),
                ('codigo_prestador', models.ForeignKey(help_text='Codigo habilitacion del prestador', on_delete=django.db.models.deletion.CASCADE, related_name='codigo_prestador_au', to='core.IpsModel')),
                ('dx_relacionado1_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico_relacionado1_salida_urgencias', to='core.Cie10Model')),
                ('dx_relacionado2_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico_relacionado2_salida_urgencias', to='core.Cie10Model')),
                ('dx_relacionado3_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico_relacionado3_salida_urgencias', to='core.Cie10Model')),
                ('dx_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico_salida_urgencias', to='core.Cie10Model')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_affiles', to=settings.AUTH_USER_MODEL)),
                ('tipo_identificacion_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_identificacion_au', to='core.TipoDocumentoModel')),
            ],
        ),
        migrations.AddIndex(
            model_name='aumodel',
            index=models.Index(fields=['numero_factura'], name='numero_fac_au_idx'),
        ),
        migrations.AddIndex(
            model_name='aumodel',
            index=models.Index(fields=['codigo_prestador'], name='codigo_prestador_au_idx'),
        ),
        migrations.AddIndex(
            model_name='aumodel',
            index=models.Index(fields=['numero_identifacion_usuario'], name='numero_identifacion_au_idx'),
        ),
        migrations.AddIndex(
            model_name='aumodel',
            index=models.Index(fields=['fecha_ingreso_usuario'], name='fecha_ingreso_au_idx'),
        ),
        migrations.AddConstraint(
            model_name='aumodel',
            constraint=models.UniqueConstraint(fields=('numero_factura', 'numero_identifacion_usuario', 'fecha_ingreso_usuario'), name='registro urgencias unico'),
        ),
    ]
