# Generated by Django 3.0.10 on 2021-03-19 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0025_auto_20210319_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuIntermediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Numero de la Factura', max_length=40, null=True)),
                ('codigo_prestador', models.CharField(help_text='Codigo del prestador', max_length=20, null=True)),
                ('tipo_identificacion_usuario', models.CharField(help_text='Tipo de identificacion', max_length=10, null=True)),
                ('numero_identifacion_usuario', models.CharField(help_text='Numero de identificación del usuario', max_length=20, null=True)),
                ('fecha_ingreso_usuario', models.CharField(help_text='Fecha Ingreso', max_length=22, null=True)),
                ('hora_ingreso_usuario', models.CharField(help_text='Hora ingreso', max_length=22, null=True)),
                ('numero_autorizacion', models.CharField(help_text='Número de autorización', max_length=30, null=True)),
                ('codigo_causa_externa', models.CharField(help_text='Codigo caso externa', max_length=20, null=True)),
                ('dx_salida', models.CharField(help_text='Diagnostico de salida', max_length=20, null=True)),
                ('dx_relacionado1_salida', models.CharField(help_text='Diagnostico relacionado 1 de salida', max_length=20, null=True)),
                ('dx_relacionado2_salida', models.CharField(help_text='Diagnostico relacionado 2 de salida', max_length=20, null=True)),
                ('dx_relacionado3_salida', models.CharField(help_text='Diagnostico relacionado 3 de salida', max_length=20, null=True)),
                ('codigo_destino_salida_usuario', models.CharField(help_text='Codigo destino a la salida de observacion', max_length=20, null=True)),
                ('codigo_estado_salida', models.CharField(help_text='Codigo estado de salida', max_length=20, null=True)),
                ('causa_basica_muerte', models.CharField(help_text='Causa basica muerte', max_length=20, null=True)),
                ('fecha_salida_usuario', models.CharField(help_text='Fecha salida', max_length=22, null=True)),
                ('hora_salida_usuario', models.CharField(help_text='Hora salida', max_length=22, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion', null=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_au_int', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='auintermediamodel',
            index=models.Index(fields=['numero_factura'], name='numero_fac_au_in_idx'),
        ),
        migrations.AddIndex(
            model_name='auintermediamodel',
            index=models.Index(fields=['codigo_prestador'], name='codigo_prestador_au_in_idx'),
        ),
        migrations.AddIndex(
            model_name='auintermediamodel',
            index=models.Index(fields=['numero_identifacion_usuario'], name='numero_identifacion_au_in_idx'),
        ),
        migrations.AddIndex(
            model_name='auintermediamodel',
            index=models.Index(fields=['fecha_ingreso_usuario'], name='fecha_ingreso_au_in_idx'),
        ),
        migrations.AddConstraint(
            model_name='auintermediamodel',
            constraint=models.UniqueConstraint(fields=('numero_factura', 'numero_identifacion_usuario', 'fecha_ingreso_usuario'), name='registro au_int unico'),
        ),
    ]
