# Generated by Django 3.0.10 on 2021-03-19 02:42

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_codigosconsultamodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0026_auto_20210319_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Numero de la Factura', max_length=30, validators=[core.validators.facturaType])),
                ('numero_identifacion_usuario', models.CharField(help_text='Numero de identificación del usuario', max_length=16, validators=[core.validators.onlyCharactersAndDigits])),
                ('fecha_ingreso_usuario', models.DateField(verbose_name='Fecha de ingreso del usuario a la instituciónn')),
                ('hora_ingreso_usuario', models.TimeField(verbose_name='Hora de ingreso del usuario a la institucion')),
                ('numero_autorizacion', models.CharField(help_text='Número de autorización', max_length=20, validators=[core.validators.facturaType])),
                ('fecha_salida_usuario', models.DateField(verbose_name='Fecha de egreso del usuario a la institución')),
                ('hora_salida_usuario', models.TimeField(verbose_name='Hora de egreso del usuario a la institución')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('active', models.BooleanField(default=True)),
                ('codigo_causa_externa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causa_externa_hospitalizacion', to='rips.CausaExternaModel')),
                ('codigo_estado_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_salida_hospitalizacion', to='rips.EstadoSalidaModel')),
                ('codigo_prestador', models.ForeignKey(help_text='Codigo habilitacion del prestador', on_delete=django.db.models.deletion.CASCADE, related_name='codigo_prestador_ah', to='core.IpsModel')),
                ('codigo_via_ingreso_institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='via_ingreso_hospitalizacion', to='rips.ViaIngresoModel')),
                ('dx_causa_muerte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causa_basica_muerte_hospitalizacion', to='core.Cie10Model')),
                ('dx_principal_egreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico_principal_egreso_hospitalizacion', to='core.Cie10Model')),
                ('dx_principal_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico_principal_ingreso_hospitalizacion', to='core.Cie10Model')),
                ('dx_relacionado1_egreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico_relacionado1_egreso_hospitalizacion', to='core.Cie10Model')),
                ('dx_relacionado2_egreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico_relacionado2_egreso_hospitalizacion', to='core.Cie10Model')),
                ('dx_relacionado3_egreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostico_relacionado3_egreso_hospitalizacion', to='core.Cie10Model')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_ah', to=settings.AUTH_USER_MODEL)),
                ('tipo_identificacion_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_identificacion_ah', to='core.TipoDocumentoModel')),
            ],
        ),
        migrations.AddIndex(
            model_name='ahmodel',
            index=models.Index(fields=['numero_factura'], name='numero_fac_ah_idx'),
        ),
        migrations.AddIndex(
            model_name='ahmodel',
            index=models.Index(fields=['codigo_prestador'], name='codigo_prestador_ah_idx'),
        ),
        migrations.AddIndex(
            model_name='ahmodel',
            index=models.Index(fields=['numero_identifacion_usuario'], name='numero_identifacion_ah_idx'),
        ),
        migrations.AddIndex(
            model_name='ahmodel',
            index=models.Index(fields=['fecha_ingreso_usuario'], name='fecha_ingreso_ah_idx'),
        ),
        migrations.AddConstraint(
            model_name='ahmodel',
            constraint=models.UniqueConstraint(fields=('numero_factura', 'numero_identifacion_usuario', 'fecha_ingreso_usuario'), name='registro hospitalizacion unico'),
        ),
    ]
