# Generated by Django 3.0.10 on 2021-03-19 02:42

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_codigosconsultamodel'),
        ('rips', '0028_auto_20210319_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Numero de la Factura', max_length=30, validators=[core.validators.facturaType])),
                ('numero_identifacion_usuario', models.CharField(help_text='Numero de identificación del usuario', max_length=16, validators=[core.validators.onlyCharactersAndDigits])),
                ('numero_autorizacion', models.CharField(help_text='Número de autorización', max_length=20, validators=[core.validators.facturaType])),
                ('nombre_generico_medicamento', models.CharField(help_text='Nombre genérico del medicamento', max_length=150)),
                ('forma_farmaceutica', models.CharField(help_text='Forma farmacéutica', max_length=100)),
                ('concentracion_medicamento', models.CharField(help_text='Concentración del medicamento', max_length=100)),
                ('unidad_medida_medicamento', models.CharField(help_text='Unidad de medida del medicamento', max_length=100)),
                ('numero_unidades', models.DecimalField(decimal_places=1, default=0.0, help_text='Número de unidades administadas o aplicadas del medicamento', max_digits=4)),
                ('valor_unitario_medicamento', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor unitario de medicamento', max_digits=20)),
                ('valor_total_medicamento', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total de medicamento', max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('active', models.BooleanField(default=True)),
                ('codigo_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cums_medicamentos_am', to='core.CumsModel')),
                ('codigo_prestador', models.ForeignKey(help_text='Codigo habilitacion del prestador', on_delete=django.db.models.deletion.CASCADE, related_name='codigo_prestador_am', to='core.IpsModel')),
                ('codigo_tipo_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cums_am', to='rips.TipoMedicamentoModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_am', to=settings.AUTH_USER_MODEL)),
                ('tipo_identificacion_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_identificacion_am', to='core.TipoDocumentoModel')),
            ],
        ),
        migrations.AddIndex(
            model_name='ammodel',
            index=models.Index(fields=['numero_factura'], name='numero_fac_am_idx'),
        ),
        migrations.AddIndex(
            model_name='ammodel',
            index=models.Index(fields=['codigo_prestador'], name='codigo_prestador_am_idx'),
        ),
        migrations.AddIndex(
            model_name='ammodel',
            index=models.Index(fields=['numero_identifacion_usuario'], name='numero_identifacion_am_idx'),
        ),
        migrations.AddIndex(
            model_name='ammodel',
            index=models.Index(fields=['codigo_medicamento'], name='codigo_medicamento_am_idx'),
        ),
        migrations.AddConstraint(
            model_name='ammodel',
            constraint=models.UniqueConstraint(fields=('numero_factura', 'numero_identifacion_usuario', 'codigo_medicamento'), name='registro medicamento unico'),
        ),
    ]
