# Generated by Django 3.0.10 on 2021-03-19 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0029_auto_20210319_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmIntermediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Numero de la Factura', max_length=200, null=True)),
                ('codigo_prestador', models.CharField(help_text='Codigo del prestador', max_length=200, null=True)),
                ('tipo_identificacion_usuario', models.CharField(help_text='Tipo de identificacion', max_length=200, null=True)),
                ('numero_identifacion_usuario', models.CharField(help_text='Numero de identificación del usuario', max_length=200, null=True)),
                ('numero_autorizacion', models.CharField(help_text='Número de autorización', max_length=200, null=True)),
                ('codigo_medicamento', models.CharField(help_text='Codigo Cums', max_length=200, null=True)),
                ('codigo_tipo_medicamento', models.CharField(help_text='Tipo medicamento', max_length=200, null=True)),
                ('nombre_generico_medicamento', models.CharField(help_text='Nombre genérico del medicamento', max_length=300, null=True)),
                ('forma_farmaceutica', models.CharField(help_text='Forma farmacéutica', max_length=200, null=True)),
                ('concentracion_medicamento', models.CharField(help_text='Concentración del medicamento', max_length=200, null=True)),
                ('unidad_medida_medicamento', models.CharField(help_text='Unidad de medida del medicamento', max_length=200, null=True)),
                ('numero_unidades', models.CharField(help_text='Número de unidades administadas o aplicadas del medicamento', max_length=100, null=True)),
                ('valor_unitario_medicamento', models.CharField(help_text='Valor unitario medicamento', max_length=100, null=True)),
                ('valor_total_medicamento', models.CharField(help_text='Valor total medicamento', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion', null=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_am_int', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='amintermediamodel',
            index=models.Index(fields=['numero_factura'], name='numero_fac_am_int_idx'),
        ),
        migrations.AddIndex(
            model_name='amintermediamodel',
            index=models.Index(fields=['codigo_prestador'], name='codigo_prestador_am_int_idx'),
        ),
        migrations.AddIndex(
            model_name='amintermediamodel',
            index=models.Index(fields=['numero_identifacion_usuario'], name='numero_identifacion_am_int_idx'),
        ),
        migrations.AddIndex(
            model_name='amintermediamodel',
            index=models.Index(fields=['codigo_medicamento'], name='codigo_medicamento_am_int_idx'),
        ),
        migrations.AddConstraint(
            model_name='amintermediamodel',
            constraint=models.UniqueConstraint(fields=('numero_factura', 'codigo_prestador', 'numero_identifacion_usuario', 'codigo_medicamento', 'nombre_generico_medicamento', 'forma_farmaceutica', 'unidad_medida_medicamento', 'concentracion_medicamento', 'numero_unidades', 'valor_total_medicamento'), name='registro am_int unico'),
        ),
    ]
