# Generated by Django 3.0.10 on 2021-03-19 02:42

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_codigosconsultamodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0030_auto_20210319_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Numero de la Factura', max_length=30, validators=[core.validators.facturaType])),
                ('numero_identifacion_usuario', models.CharField(help_text='Numero de identificación del usuario', max_length=16, validators=[core.validators.onlyCharactersAndDigits])),
                ('numero_autorizacion', models.CharField(help_text='Número de autorización', max_length=20, validators=[core.validators.facturaType])),
                ('codigo_servicio', models.CharField(help_text='Código del servicio', max_length=20, null=True, validators=[core.validators.onlyCharactersAndDigits])),
                ('nombre_servicio', models.CharField(help_text='Nombre del servicio', max_length=150, validators=[core.validators.onlyCharactersSpacesAndPunctuation])),
                ('cantidad', models.DecimalField(decimal_places=1, default=0.0, help_text='Cantidad', max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor unitario', max_digits=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total', max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('active', models.BooleanField(default=True)),
                ('codigo_prestador', models.ForeignKey(help_text='Codigo habilitacion del prestador', on_delete=django.db.models.deletion.CASCADE, related_name='codigo_prestador_at', to='core.IpsModel')),
                ('codigo_tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_servicio_otros_servicios', to='rips.TipoServicioModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_at', to=settings.AUTH_USER_MODEL)),
                ('tipo_identificacion_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_identificacion_at', to='core.TipoDocumentoModel')),
            ],
        ),
        migrations.AddIndex(
            model_name='atmodel',
            index=models.Index(fields=['numero_factura'], name='numero_fac_at_idx'),
        ),
        migrations.AddIndex(
            model_name='atmodel',
            index=models.Index(fields=['codigo_prestador'], name='codigo_prestador_at_idx'),
        ),
        migrations.AddIndex(
            model_name='atmodel',
            index=models.Index(fields=['numero_identifacion_usuario'], name='numero_identifacion_at_idx'),
        ),
        migrations.AddIndex(
            model_name='atmodel',
            index=models.Index(fields=['nombre_servicio'], name='nombre_servicio_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='atmodel',
            constraint=models.UniqueConstraint(fields=('numero_factura', 'numero_identifacion_usuario', 'nombre_servicio'), name='registro at unico'),
        ),
    ]
