# Generated by Django 3.0.10 on 2021-03-19 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rips', '0031_auto_20210319_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtIntermediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Numero de la Factura', max_length=40, null=True)),
                ('codigo_prestador', models.CharField(help_text='Codigo del prestador', max_length=20, null=True)),
                ('tipo_identificacion_usuario', models.CharField(help_text='Tipo de identificacion', max_length=10, null=True)),
                ('numero_identifacion_usuario', models.CharField(help_text='Numero de identificación del usuario', max_length=20, null=True)),
                ('numero_autorizacion', models.CharField(help_text='Número de autorización', max_length=20, null=True)),
                ('codigo_tipo_servicio', models.CharField(help_text='Codigo tipo del servicio', max_length=20, null=True)),
                ('codigo_servicio', models.CharField(help_text='Código del servicio', max_length=20, null=True)),
                ('nombre_servicio', models.CharField(help_text='Nombre del servicio', max_length=200, null=True)),
                ('cantidad', models.DecimalField(decimal_places=1, default=0.0, help_text='Cantidad', max_digits=20)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor unitario', max_digits=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total', max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_at_int', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='atintermediamodel',
            index=models.Index(fields=['numero_factura'], name='numero_fac_at_int_idx'),
        ),
        migrations.AddIndex(
            model_name='atintermediamodel',
            index=models.Index(fields=['codigo_prestador'], name='codigo_prestador_at_int_idx'),
        ),
        migrations.AddIndex(
            model_name='atintermediamodel',
            index=models.Index(fields=['numero_identifacion_usuario'], name='numero_identifacion_at_int_idx'),
        ),
        migrations.AddIndex(
            model_name='atintermediamodel',
            index=models.Index(fields=['codigo_servicio'], name='codigo_servicio_at_int_idx'),
        ),
        migrations.AddIndex(
            model_name='atintermediamodel',
            index=models.Index(fields=['nombre_servicio'], name='nombre_servicio_at_int_idx'),
        ),
        migrations.AddConstraint(
            model_name='atintermediamodel',
            constraint=models.UniqueConstraint(fields=(
                'numero_factura', 
                'codigo_prestador',
                'numero_identifacion_usuario', 
                'tipo_identificacion_usuario', 
                'codigo_tipo_servicio',
                'codigo_servicio',
                'nombre_servicio',
                'cantidad',
                'valor_unitario',
                'valor_total'
                ), name='registro at_int unico'),
        ),
    ]
