from autorizaciones.models.plan_servicio import planServicioModel
from autorizaciones.models.codigo_clasificacion_triage import codigoClasificacionTriageModel
from autorizaciones.models.estado_autorizacion import estadoAutorizacionModel
from autorizaciones.models.autorizacion import autorizacionModel
from autorizaciones.models.objeto_autorizacion import objetoAutorizacionModel