# Generated by Django 3.0.10 on 2021-04-05 22:08

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqrs', '0002_tipopqrsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='pqrsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_radicacion', models.CharField(help_text='Código de radicación de la solicitud', max_length=30, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('description', models.TextField(help_text='Descripción de la solicitud', max_length=2000, validators=[core.validators.noSpacesStartEnd])),
                ('area', models.CharField(help_text='Área de la solicitud', max_length=50, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('causal', models.CharField(help_text='Causal de la solicitud', max_length=50, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('tecnologia', models.CharField(help_text='Tecnología de la solicitud', max_length=50, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('observaciones', models.TextField(help_text='Observaciones de la solicitud', max_length=500, validators=[core.validators.noSpacesStartEnd])),
                ('observaciones_cierre', models.TextField(help_text='Observaciones de cierre de la solicitud', max_length=500, validators=[core.validators.noSpacesStartEnd])),
                ('ultima_observacion', models.TextField(help_text='Última observacion realizada sobre el proceso de la solicitud', max_length=500, validators=[core.validators.noSpacesStartEnd])),
                ('codigo', models.CharField(help_text='Código de la solicitud', max_length=50, null=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('fecha_recepcion', models.DateField(help_text='Fecha de recepción de la solicitud', verbose_name=())),
                ('duracion_gestion', models.PositiveSmallIntegerField(help_text='Duración de la gestión de la solicitud')),
                ('duracion_permitida', models.PositiveSmallIntegerField(help_text='Duración permitida de la gestión de la solicitud')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_pqrs', to=settings.AUTH_USER_MODEL)),
                ('tipo_pqrs_id', models.ForeignKey(db_column='tipo_pqrs_id', help_text='Tipo de solicitud', on_delete=django.db.models.deletion.PROTECT, related_name='pqrs_tipo_pqrs', to='pqrs.tipoPqrsModel')),
                ('unidad_duracion_id', models.ForeignKey(db_column='unidad_duracion_id', help_text='Unidad de duración', on_delete=django.db.models.deletion.PROTECT, related_name='pqrs_unidad_duracion', to='pqrs.unidadDuracionModel')),
            ],
        ),
    ]
