# Generated by Django 3.0.10 on 2022-09-19 14:43

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0054_estadospacientemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('censo', '0011_auto_20220919_1443'),
        ('afiliados', '0004_auto_20220919_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstanciaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(help_text='Fecha de ingreso del paciente', validators=[core.validators.currentDate])),
                ('fecha_egreso', models.DateField(blank=True, help_text='Fecha de egreso del paciente', null=True, validators=[core.validators.currentDate])),
                ('dias_estancia', models.PositiveIntegerField(blank=True, default=0, help_text='Dias de estancia del paceinte en el censo', validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('reingreso', models.BooleanField(default=False, help_text='Indica si el registro es un reingreso')),
                ('estado', models.BooleanField(default=True)),
                ('dx_sindromatico', models.BooleanField(default=False)),
                ('dx_alto_riesgo', models.BooleanField(default=False)),
                ('estancia_prolongada', models.BooleanField(default=False)),
                ('cohorte_seguimiento', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('afiliado_id', models.ForeignKey(db_column='afiliado_id', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_afiliado', to='afiliados.afiliadoModel')),
                ('codigo_ips_id', models.ForeignKey(db_column='codigo_ips_id', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_ips', to='core.IpsModel')),
                ('condicion_alta_id', models.ForeignKey(blank=True, db_column='condicion_alta_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estancia_condicion_alta', to='censo.condicionAltaCensoModel')),
                ('dx_actual', models.ForeignKey(db_column='dx_actual', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_cie10_actual', to='core.Cie10Model')),
                ('dx_egreso', models.ForeignKey(blank=True, db_column='dx_egreso', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estancia_cie10_egreso', to='core.Cie10Model')),
                ('dx_ingreso', models.ForeignKey(db_column='dx_ingreso', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_cie10_ingreso', to='core.Cie10Model')),
                ('origen_evento_id', models.ForeignKey(db_column='origen_evento_id', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_origen_evento', to='censo.origenEventoModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_estancia', to=settings.AUTH_USER_MODEL)),
                ('tipo_ingreso_id', models.ForeignKey(db_column='tipo_ingreso_id', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_tipo_ingreso', to='censo.tipoIngresoModel')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosEstanciaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de registro del servicio', validators=[core.validators.currentDate])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('estancia_id', models.ForeignKey(db_column='estancia_id', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_servicio', to='estancias.EstanciaModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_servicio_estancia', to=settings.AUTH_USER_MODEL)),
                ('tipo_habitacion_id', models.ForeignKey(db_column='tipo_habitacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='tipo_habitacion_servico_estancia', to='censo.tipoHabitacionModel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='estanciamodel',
            constraint=models.UniqueConstraint(condition=models.Q(estado=True), fields=('afiliado_id', 'estado'), name='Solo una estancia activa por usuario'),
        ),
    ]
