# Generated by Django 3.0.10 on 2023-01-03 21:40

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('censo', '0013_auto_20230103_2140'),
        ('estancias', '0002_auto_20221228_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='estanciamodel',
            name='fecha_registro_egreso',
            field=models.DateField(blank=True, help_text='Fecha registro del egreso del paciente', null=True, validators=[core.validators.currentDate]),
        ),
        migrations.AddField(
            model_name='estanciamodel',
            name='usuario_egreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_egreso_estancia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estanciamodel',
            name='origen_evento_id',
            field=models.ForeignKey(db_column='origen_evento_id', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_origen_evento', to='censo.OrigenEventoModel'),
        ),
        migrations.AlterField(
            model_name='estanciamodel',
            name='tipo_ingreso_id',
            field=models.ForeignKey(db_column='tipo_ingreso_id', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_tipo_ingreso', to='censo.TipoIngresoModel'),
        ),
        migrations.AlterField(
            model_name='serviciosestanciamodel',
            name='tipo_habitacion_id',
            field=models.ForeignKey(db_column='tipo_habitacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='tipo_habitacion_servico_estancia', to='censo.TipoHabitacionModel'),
        ),
    ]
