# Generated by Django 3.0.10 on 2023-01-04 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0014_auto_20230104_2241'),
        ('estancias', '0003_auto_20230103_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estanciamodel',
            name='origen_evento_id',
            field=models.ForeignKey(db_column='origen_evento_id', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_origen_evento', to='censo.OrigenEventoModel'),
        ),
        migrations.AlterField(
            model_name='estanciamodel',
            name='tipo_ingreso_id',
            field=models.ForeignKey(db_column='tipo_ingreso_id', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_tipo_ingreso', to='censo.TipoIngresoModel'),
        ),
        migrations.AlterField(
            model_name='serviciosestanciamodel',
            name='tipo_habitacion_id',
            field=models.ForeignKey(db_column='tipo_habitacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='tipo_habitacion_servico_estancia', to='censo.TipoHabitacionModel'),
        ),
    ]
