# Generated by Django 3.0.10 on 2023-01-10 04:15

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_tiposasesoresmodel'),
        ('estancias', '0005_auto_20230110_0415'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objeciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjecionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_objecion', models.DateField(verbose_name='Fecha objecion')),
                ('nota_objecion', models.TextField(blank=True, help_text='Observaciones objecion', null=True)),
                ('cantidad', models.IntegerField(default=0, help_text='Solicitud asesor. 0: no requerido, 1: requerido, 2: revisado, 3: solicitado', validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('valor', models.DecimalField(decimal_places=1, help_text='Valor objecion', max_digits=4, null=True, validators=[core.validators.onlyDigitsAndPoints])),
                ('created', models.DateTimeField(auto_now=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('cums', models.ForeignKey(blank=True, db_column='cums', help_text='Id del registro cums relacionado con la objecion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cums_objeciones', to='core.CumsModel')),
                ('cups', models.ForeignKey(blank=True, db_column='cups', help_text='Id del registro cups relacionado con la objecion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups_medicamentos', to='core.CupsModel')),
                ('estancia_id', models.ForeignKey(db_column='estancia_id', help_text='Estancia relacionada', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_medicamentos', to='estancias.EstanciaModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_objecion', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(db_column='tipo', help_text='Codigo del tipo de objecion', on_delete=django.db.models.deletion.PROTECT, related_name='objecion_tipo_objecion', to='objeciones.TipoObjecionModel')),
            ],
        ),
    ]
