# Generated by Django 3.0.10 on 2023-01-10 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0006_auto_20230110_1845'),
        ('medicamentos', '0004_auto_20230110_1843'),
        ('objeciones', '0002_objecionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecionmodel',
            name='medicamento_id',
            field=models.ForeignKey(blank=True, db_column='medicamento_id', help_text='Estancia relacionada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicamento_objeciones', to='medicamentos.MedicamentoModel'),
        ),
        migrations.AlterField(
            model_name='objecionmodel',
            name='cantidad',
            field=models.IntegerField(default=1, help_text='Solicitud asesor. 0: no requerido, 1: requerido, 2: revisado, 3: solicitado', validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='objecionmodel',
            name='estancia_id',
            field=models.ForeignKey(db_column='estancia_id', help_text='Estancia relacionada', on_delete=django.db.models.deletion.PROTECT, related_name='estancia_objeciones', to='estancias.EstanciaModel'),
        ),
    ]
