# Generated by Django 3.0.10 on 2023-01-10 20:02

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objeciones', '0003_auto_20230110_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoobjecionmodel',
            name='grupo',
            field=models.CharField(default='', help_text='Grupo objecion', max_length=100, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndSpaces]),
            preserve_default=False,
        ),
    ]
