# Generated by Django 3.0.10 on 2023-01-10 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objeciones', '0004_tipoobjecionmodel_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecionmodel',
            name='valor',
            field=models.IntegerField(default=1, help_text='Valor objecion', validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
