# Generated by Django 3.0.10 on 2022-09-05 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_estadospacientemodel'),
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorteafiliadomodel',
            name='cohorte_id',
            field=models.ForeignKey(db_column='cohorte_id', help_text='Cohorte del afiliado', on_delete=django.db.models.deletion.PROTECT, related_name='afiliado_cohorte_cohorte', to='core.CohorteModel'),
        ),
    ]
