# Generated by Django 3.0.10 on 2022-09-19 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0007_auto_20220919_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohorteafiliadomodel',
            name='cohorte_id',
        ),
    ]
