# Generated by Django 3.0.10 on 2022-09-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20220919_2138'),
        ('afiliados', '0010_auto_20220920_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorteafiliadomodel',
            name='cohorte_id',
            field=models.ForeignKey(db_column='cohorte_id', help_text='Cohorte del afiliado', on_delete=django.db.models.deletion.PROTECT, related_name='afiliado_cohorte_cohorte', to='core.CohorteModel'),
        ),
        migrations.AddConstraint(
            model_name='cohorteafiliadomodel',
            constraint=models.UniqueConstraint(fields=('afiliado_id', 'cohorte_id'), name='Las cohortes deben ser unicas para cada afiliado'),
        ),
    ]
