# Generated by Django 3.0.10 on 2021-05-13 20:08

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20210513_0357'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medimas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pacienteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.CharField(help_text='identificador del paceinte', max_length=100, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('fecha_fallecimiento', models.DateField(null=True, verbose_name='Fecha Fallecimiento')),
                ('edad', models.PositiveIntegerField(help_text='Edad del paciente', validators=[core.validators.noSpacesStartEnd, core.validators.onlyDigits])),
                ('fecha_creacion', models.DateTimeField(verbose_name=())),
                ('nombre_pais_residencia', models.CharField(help_text='Nombre pais de residencia paciente', max_length=100, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('nombre_regional_agrupada_residencia', models.CharField(help_text='Nombre regional agrupada paciente', max_length=100, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('nombre_division_politica_residencia', models.CharField(help_text='Nombre departamento de residencia paciente', max_length=100, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('nombre_ciudad_residencia', models.CharField(help_text='Nombre ciudad de residencia paciente', max_length=100, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('numero_de_documento', models.CharField(db_column='numero_de_documento', help_text='Identificacion del paciente', max_length=100, unique=True, validators=[core.validators.noSpacesStartEnd, core.validators.onlyCharactersAndDigits])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=())),
                ('active', models.BooleanField(default=True)),
                ('cod_ciudad_residencia', models.ForeignKey(db_column='cod_ciudad_residencia', help_text='Municipio (ciudad) donde reside el paciente', on_delete=django.db.models.deletion.PROTECT, related_name='paciente_municipio', to='core.MunicipioModel')),
                ('cod_division_politica_residencia', models.ForeignKey(db_column='cod_division_politica_residencia', help_text='Departamento donde reside el paciente', on_delete=django.db.models.deletion.PROTECT, related_name='paciente_departamento', to='core.DepartamentoModel')),
                ('cod_pais_residencia', models.ForeignKey(db_column='cod_pais_residencia', help_text='Código país', on_delete=django.db.models.deletion.PROTECT, related_name='paciente_pais', to='core.PaisModel')),
                ('grupo_etnico', models.ForeignKey(db_column='grupo_etnico', help_text='Pertenencia étnica del paciente', on_delete=django.db.models.deletion.PROTECT, related_name='paciente_pertenencia_etnica', to='core.OrigenEtnicoModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_create_paciente', to=settings.AUTH_USER_MODEL)),
                ('sexo', models.ForeignKey(db_column='sexo', on_delete=django.db.models.deletion.PROTECT, related_name='paciente_sexo', to='core.SexoModel')),
                ('tipo_de_documento', models.ForeignKey(db_column='tipo_de_documento', help_text='Tipo de identificación del paciente', on_delete=django.db.models.deletion.PROTECT, related_name='paciente_tipo_identificacion', to='core.TipoDocumentoModel')),
            ],
        ),
    ]
